create extension if not exists pg_trgm;
create extension if not exists unaccent;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.generate_tool_slug()
returns trigger
language plpgsql
as $$
begin
  if new.slug is null or new.slug = '' then
    new.slug := lower(regexp_replace(unaccent(new.name), '[^a-zA-Zа-яА-Я0-9]+', '-', 'g'));
    new.slug := trim(both '-' from new.slug);
  end if;
  return new;
end;
$$;

create table if not exists public.tools (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text unique,
  url text not null,
  affiliate_url text,
  description text not null,
  category text not null,
  pricing text not null check (pricing in ('Бесплатно', 'Фримиум', 'Платно', 'Пробный период')),
  domain text not null,
  tags text[] not null default '{}'::text[],
  commission_rate numeric(4,3) not null default 0.20 check (commission_rate >= 0 and commission_rate <= 1),
  click_count bigint not null default 0,
  featured boolean not null default false,
  verified boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.clicks (
  id bigint generated by default as identity primary key,
  tool_id bigint not null references public.tools(id) on delete cascade,
  ip inet,
  user_agent text,
  referer text,
  country text,
  device_type text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  clicked_at timestamptz not null default now()
);

create materialized view if not exists public.tools_analytics as
select
  t.id,
  t.name,
  t.slug,
  t.category,
  t.pricing,
  t.domain,
  t.commission_rate,
  t.click_count as clicks,
  count(c.id) as total_click_rows,
  count(distinct c.ip) as unique_visitors,
  count(*) filter (where c.device_type = 'mobile') as mobile_clicks,
  count(*) filter (where c.device_type = 'desktop') as desktop_clicks,
  round((t.click_count::numeric * 0.15 * 29 * t.commission_rate), 2) as estimated_revenue,
  max(t.updated_at) as updated_at
from public.tools t
left join public.clicks c on c.tool_id = t.id
group by t.id;

create unique index if not exists tools_analytics_id_idx on public.tools_analytics (id);
create index if not exists tools_slug_idx on public.tools (slug);
create index if not exists tools_category_idx on public.tools (category);
create index if not exists tools_pricing_idx on public.tools (pricing);
create index if not exists tools_domain_idx on public.tools (domain);
create index if not exists tools_featured_idx on public.tools (featured);
create index if not exists tools_verified_idx on public.tools (verified);
create index if not exists clicks_tool_id_clicked_at_idx on public.clicks (tool_id, clicked_at desc);
create index if not exists clicks_country_idx on public.clicks (country);
create index if not exists clicks_device_type_idx on public.clicks (device_type);
create index if not exists tools_search_idx on public.tools using gin (to_tsvector('russian', coalesce(name, '') || ' ' || coalesce(description, '') || ' ' || coalesce(category, '')));
create index if not exists tools_search_trgm_idx on public.tools using gin (name gin_trgm_ops);

alter table public.tools enable row level security;
alter table public.clicks enable row level security;

create policy if not exists "Public can read tools"
on public.tools for select
using (true);

create policy if not exists "Service role can write tools"
on public.tools for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');

create policy if not exists "Authenticated users can insert clicks"
on public.clicks for insert
with check (auth.role() in ('authenticated', 'service_role'));

create policy if not exists "Service role can read clicks"
on public.clicks for select
using (auth.role() = 'service_role');

create trigger tools_set_slug
before insert or update on public.tools
for each row execute function public.generate_tool_slug();

create trigger tools_set_updated_at
before update on public.tools
for each row execute function public.set_updated_at();

create or replace function public.increment_tool_click_count()
returns trigger
language plpgsql
as $$
begin
  update public.tools
  set click_count = click_count + 1,
      updated_at = now()
  where id = new.tool_id;
  return new;
end;
$$;

create trigger clicks_increment_tool_click_count
after insert on public.clicks
for each row execute function public.increment_tool_click_count();
